pipeline:
  test:
    image: golang
    when:
      branch:
        - master
        - dev
    commands:
      - go test -v ./...

  build:
    image: golang
    when:
      branch:
        - master
    commands:
      - docker build .
      - docker
