kind: pipeline
name: default

steps:
  - name: test
    image: golang
    commands:
      - go test -v ./...
    when:
      branch:
        - master
        - dev

  - name: web
    image: golang
    commands:
      - docker build .
    when:
      branch:
        - master
